### ISSUE TITLE
retarget open PRs?

### ISSUE THREAD

**Issue by non** [dfm/rename-github-default-branch#1]
Thanks for this great tool!

I was wondering if you could add something to the README about open PRs. Does this script update them? If not, that's fine, but either way it would be nice to mention this.

**Comment by dfm** [comment]
This is a great question! This will not change open PRs, but it's possible that it could be updated to do that (for pull requests into the repo whose default branch is being renamed - I think that the other direction is not possible). I'll add a note. Thanks!
